namespace:
  name: sandbox

service:
  protocol: TCP
  port: 4111
  targetPort: 3111
  type: ClusterIP

image:
  repository: naturallyunintelligent/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

probes:
  livenessProbe:
    path: /healthz
    port: 3111
  readinessProbe:
    path: /healthz
    port: 3111
