namespace:
  name: sandbox

service:
  protocol: TCP
  port: 4111
  targetPort: 3111
  type: ClusterIP

image:
  repository: naturallyunintelligent/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz

readinessProbe:
  httpGet:
    path: /healthz